INSERT INTO STATES (NAME) VALUES
('UTTAR PRADESH'),
('KARNATAKA'),
('DELHI');

INSERT INTO CITIES (NAME,STATE_ID) VALUES
( 'GHAZIABAD' ,1),
('BANGALORE',2),
('NEW DELHI',3);


INSERT INTO ROLES (ROLE_NAME) VALUES
('ADMIN'),
('CUSTOMER'),
('ATTENDANT');