INSERT INTO USER_ROLES (ROLE_ID,ROLE_NAME) VALUES (1,'ADMIN');
INSERT INTO USER_ROLES (ROLE_ID,ROLE_NAME) VALUES (2,'ATTENDANT');
INSERT INTO USER_ROLES (ROLE_ID,ROLE_NAME) VALUES (3,'CUSTOMER');

INSERT INTO USERS_PERMISSIONS (PERMISSION_ID,PERMISSION_NAME) VALUES (1,'WRITE');
INSERT INTO USERS_PERMISSIONS (PERMISSION_ID,PERMISSION_NAME) VALUES (2,'READ');

INSERT INTO STATES (STATE_ID,STATE_NAME) VALUES (1,'UTTAR PRADESH');
INSERT INTO STATES (STATE_ID,STATE_NAME) VALUES (2,'DELHI');
INSERT INTO STATES (STATE_ID,STATE_NAME) VALUES (3,'KARNATAKA');
INSERT INTO STATES (STATE_ID,STATE_NAME) VALUES (4,'MAHARASTRA');
INSERT INTO STATES (STATE_ID,STATE_NAME) VALUES (5,'HARYANA');

INSERT INTO CITIES (CITY_ID,CITY_NAME,STATE_ID) VALUES (1,'GHAZIABAD',1);
INSERT INTO CITIES (CITY_ID,CITY_NAME,STATE_ID) VALUES (2,'NEW DELHI',2);
INSERT INTO CITIES (CITY_ID,CITY_NAME,STATE_ID) VALUES (3,'BENGALURU',3);
INSERT INTO CITIES (CITY_ID,CITY_NAME,STATE_ID) VALUES (4,'MUMBAI',4);
INSERT INTO CITIES (CITY_ID,CITY_NAME,STATE_ID) VALUES (5,'GURUGRAM',5);
