INSERT INTO STATES (STATE_NAME)
VALUES ('UTTAR PRADESH'),
       ('KARNATAKA'),
       ('DELHI');

INSERT INTO CITIES (NAME, STATE_NAME)
VALUES ('GHAZIABAD', 'UTTAR PRADESH'),
       ('BANGALORE', 'KARNATAKA'),
       ('NEW DELHI', 'DELHI');


INSERT INTO ROLES (ROLE_NAME)
VALUES ('ADMIN'),
       ('CUSTOMER'),
       ('ATTENDANT');