DROP TABLE IF EXISTS STATES;
CREATE TABLE STATES
(
    ID         INT AUTO_INCREMENT PRIMARY KEY,
    STATE_NAME VARCHAR2(250) NOT NULL
);

DROP TABLE IF EXISTS CITIES;
CREATE TABLE CITIES
(
    ID         INT AUTO_INCREMENT PRIMARY KEY,
    NAME       VARCHAR2(250) NOT NULL,
    STATE_NAME VARCHAR2(250) NOT NULL,
    CONSTRAINT FK_STATE_NAME FOREIGN KEY (STATE_NAME) REFERENCES STATES (STATE_NAME)
);

DROP TABLE IF EXISTS PARKING_FACILITIES;
CREATE TABLE PARKING_FACILITIES
(
    ID        INT AUTO_INCREMENT PRIMARY KEY,
    NAME      VARCHAR(250)   NOT NULL,
    ADDRESS   VARCHAR2(1000) NOT NULL,
    LONGITUDE VARCHAR2(1000),
    LATITUDE  VARCHAR2(1000),
    CITY_ID   INT,
    CONSTRAINT FK_CITY_ID FOREIGN KEY (CITY_ID) REFERENCES CITIES (ID)
);

DROP TABLE IF EXISTS PARKING_SLOTS;
CREATE TABLE PARKING_SLOTS
(
    ID          INT AUTO_INCREMENT PRIMARY KEY,
    FACILITY_ID INT,
    SLOT_NUMBER INT,
    TYPE        VARCHAR(50) NOT NULL,
    LONGITUDE   VARCHAR2(1000),
    LATITUDE    VARCHAR2(1000),
    CONSTRAINT FK_FACILITY_ID FOREIGN KEY (FACILITY_ID) REFERENCES PARKING_FACILITIES (ID)
);

DROP TABLE IF EXISTS VEHICLE_DETAILS;
CREATE TABLE VEHICLE_DETAILS
(
    ID                  INT AUTO_INCREMENT PRIMARY KEY,
    TYPE                VARCHAR2(50)  NOT NULL,
    REGISTRATION_NUMBER VARCHAR2(500),
    COLOR               VARCHAR2(100) NOT NULL,
    VEHICLE_IMAGE       BLOB
);

DROP TABLE IF EXISTS USER_DETAILS;
CREATE TABLE USER_DETAILS
(
    ID                     INT AUTO_INCREMENT PRIMARY KEY,
    USER_NAME              VARCHAR2(200) UNIQUE,
    EMAIL_ID               VARCHAR2(5500) UNIQUE,
    PHONE_NUMBER           NUMBER(11) UNIQUE,
    FIRST_NAME             VARCHAR2(1000) NOT NULL,
    LAST_NAME              VARCHAR2(1000) NOT NULL,
    ADDRESS                VARCHAR2(1000) NOT NULL,
    LONGITUDE              VARCHAR2(1000),
    LATITUDE               VARCHAR2(1000),
    DRIVING_LICENSE_NUMBER VARCHAR2(1000),
    AADHAR_NUMBER          VARCHAR2(1000),
    DRIVING_LICENSE_IMG    BLOB,
    AADHAR_IMAGE           BLOB,
    USER_IMAGE             BLOB
);

DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS
(
    ID       INT AUTO_INCREMENT PRIMARY KEY,
    EMAIL_ID VARCHAR2(200) UNIQUE NOT NULL,
    PASSWORD VARCHAR2(500)        NOT NULL,
    ENABLED  BOOLEAN DEFAULT TRUE,
    CONSTRAINT FK_EMAIL_ID FOREIGN KEY (EMAIL_ID) REFERENCES USER_DETAILS (EMAIL_ID)
);

DROP TABLE IF EXISTS ROLES;
CREATE TABLE ROLES
(
    ID   INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE USERS_ROLES
(
    ID       INT AUTO_INCREMENT PRIMARY KEY,
    USER_EMAIL VARCHAR2(200) NOT NULL,
    ROLE VARCHAR2(50) NOT NULL,
    CONSTRAINT FK_USER_EMAIL FOREIGN KEY (USER_EMAIL) REFERENCES USERS (EMAIL_ID),
    CONSTRAINT FK_ROLE_NAME FOREIGN KEY (ROLE) REFERENCES ROLES (NAME)
);

DROP TABLE IF EXISTS BOOKINGS;
CREATE TABLE BOOKINGS
(
    ID                 INT AUTO_INCREMENT PRIMARY KEY,
    SLOT_ID            INT           NOT NULL,
    USER_NAME          VARCHAR2(200) NOT NULL,
    VEHICLE_ID         INT           NOT NULL,
    BOOKING_START_DATE DATE          NOT NULL,
    CHECK_IN_TIME      TIMESTAMP     NOT NULL,
    CHECK_OUT_TIME     TIMESTAMP     NOT NULL,
    CONSTRAINT FK_BOOKING_SLOT_ID FOREIGN KEY (SLOT_ID) REFERENCES PARKING_SLOTS (ID),
    CONSTRAINT FK_BOOKING_USER_ID FOREIGN KEY (USER_NAME) REFERENCES USER_DETAILS (USER_NAME),
    CONSTRAINT FK_BOOKING_VEHICLE_ID FOREIGN KEY (VEHICLE_ID) REFERENCES VEHICLE_DETAILS (ID)
);




