DROP TABLE IF EXISTS USER_ROLES;
CREATE TABLE USER_ROLES
(
    ID   INT AUTO_INCREMENT PRIMARY KEY,
    ROLE_ID INT NOT NULL UNIQUE ,
    ROLE_NAME VARCHAR2(50) NOT NULL UNIQUE
);

DROP TABLE IF EXISTS USERS_PERMISSIONS;
CREATE TABLE USERS_PERMISSIONS
(
    ID   INT AUTO_INCREMENT PRIMARY KEY,
    PERMISSION_ID INT NOT NULL UNIQUE ,
    PERMISSION_NAME VARCHAR2(50) NOT NULL UNIQUE
);

DROP TABLE IF EXISTS STATES;
CREATE TABLE STATES
(
    ID         INT AUTO_INCREMENT PRIMARY KEY,
    STATE_ID INT NOT NULL  UNIQUE ,
    STATE_NAME VARCHAR2(250) NOT NULL
);

DROP TABLE IF EXISTS CITIES;
CREATE TABLE CITIES
(
    ID         INT AUTO_INCREMENT PRIMARY KEY,
    CITY_ID INT NOT NULL  UNIQUE ,
    CITY_NAME       VARCHAR2(250) NOT NULL,
    STATE_ID INT NOT NULL,
    CONSTRAINT FK_STATE_NAME FOREIGN KEY (STATE_ID) REFERENCES STATES (STATE_ID)
);

DROP TABLE IF EXISTS PARKING_FACILITIES;
CREATE TABLE PARKING_FACILITIES
(
    ID        INT AUTO_INCREMENT PRIMARY KEY,
    NAME      VARCHAR(250)   NOT NULL,
    ADDRESS   VARCHAR2(1000) NOT NULL,
    LONGITUDE VARCHAR2(1000),
    LATITUDE  VARCHAR2(1000),
    CITY_ID   INT,
    CONSTRAINT FK_CITY_ID FOREIGN KEY (CITY_ID) REFERENCES CITIES (ID)
);

DROP TABLE IF EXISTS PARKING_SLOTS;
CREATE TABLE PARKING_SLOTS
(
    ID          INT AUTO_INCREMENT PRIMARY KEY,
    FACILITY_ID INT,
    SLOT_NUMBER INT,
    TYPE        VARCHAR(50) NOT NULL,
    LONGITUDE   VARCHAR2(1000),
    LATITUDE    VARCHAR2(1000),
    CONSTRAINT FK_FACILITY_ID FOREIGN KEY (FACILITY_ID) REFERENCES PARKING_FACILITIES (ID)
);

DROP TABLE IF EXISTS VEHICLE_DETAILS;
CREATE TABLE VEHICLE_DETAILS
(
    ID                  INT AUTO_INCREMENT PRIMARY KEY,
    TYPE                VARCHAR2(50)  NOT NULL,
    REGISTRATION_NUMBER VARCHAR2(500) NOT NULL UNIQUE,
    COLOR               VARCHAR2(100) NOT NULL,
    VEHICLE_IMAGE       BLOB
);

DROP TABLE IF EXISTS USER_INFO_DETAILS;
CREATE TABLE USER_INFO_DETAILS
(
    ID                     INT AUTO_INCREMENT PRIMARY KEY,
    USER_NAME              VARCHAR2(200) UNIQUE,
    EMAIL_ID               VARCHAR2(5500) UNIQUE,
    PHONE_NUMBER           NUMBER(11) UNIQUE,
    FIRST_NAME             VARCHAR2(1000) NOT NULL,
    LAST_NAME              VARCHAR2(1000) NOT NULL,
    ADDRESS                VARCHAR2(1000) NOT NULL,
    LONGITUDE              VARCHAR2(1000),
    LATITUDE               VARCHAR2(1000),
    DRIVING_LICENSE_NUMBER VARCHAR2(1000),
    AADHAR_NUMBER          VARCHAR2(1000),
    DRIVING_LICENSE_IMG    BLOB,
    AADHAR_IMAGE           BLOB,
    USER_IMAGE             BLOB
);

DROP TABLE IF EXISTS BOOKINGS;
CREATE TABLE BOOKINGS
(
    ID                          INT AUTO_INCREMENT PRIMARY KEY,
    SLOT_ID                     INT           NOT NULL,
    EMAIL_ID                    VARCHAR2(200) NOT NULL,
    VEHICLE_REGISTRATION_NUMBER VARCHAR2(200) NOT NULL,
    BOOKING_START_DATE          DATE          NOT NULL,
    CHECK_IN_TIME               TIMESTAMP     NOT NULL,
    CHECK_OUT_TIME              TIMESTAMP     NOT NULL,
    CONSTRAINT FK_BOOKING_SLOT_ID FOREIGN KEY (SLOT_ID) REFERENCES PARKING_SLOTS (ID),
    CONSTRAINT FK_BOOKING_EMAIL_ID FOREIGN KEY (EMAIL_ID) REFERENCES USER_INFO_DETAILS (EMAIL_ID),
    CONSTRAINT FK_BOOKING_VEHICLE_ID FOREIGN KEY (VEHICLE_REGISTRATION_NUMBER) REFERENCES VEHICLE_DETAILS (REGISTRATION_NUMBER)
);






